name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'
      
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      libraryName: crosswindow
      cmakeInstallationPath: crosswindow-installation
      tagName: 2.3.1
      msvc2019TargetZip: crosswindow-${{ github.ref_name }}-msvc2019.zip
    steps:
      - name: git clone
        shell: cmd
        run: git clone --recursive https://github.com/alaingalvan/CrossWindow.git # && cd CrossWindow && git checkout ${{ env.tagName }}
        
      - name: curl x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
        shell: cmd
        run: |
          curl https://github.com/2641797006/c/blob/master/GCC-zip/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z?raw=true -L --output x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z &&^
          dir &&^
          7z.exe x x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
        
      - name: curl cmake-3.22.2-windows-x86_64.zip
        shell: cmd
        run: |
          curl https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-windows-x86_64.zip -L --output cmake-3.22.2-windows-x86_64.zip &&^
          dir &&^
          7z.exe x cmake-3.22.2-windows-x86_64.zip
        
      - name: set PATH, check mingw version, cmake generate, build and install
        shell: cmd
        run: |
          set PATH=^
          ${{ github.workspace }}\cmake-3.22.2-windows-x86_64\bin;^
          %PATH%
          set CD_LINUX=%CD:\=/%
          cd CrossWindow && ^
          cmake.exe -G "Visual Studio 16 2019" ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DCMAKE_INSTALL_PREFIX="cmake-build/${{ env.cmakeInstallationPath }}" ^
          -B./cmake-build &&^
          cd cmake-build &&^
          cmake --build . --config Release --target ALL_BUILD -v -- /maxcpucount &&^
          dir /s &&^
          cmake --install . 
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "CrossWindow/cmake-build/${{ env.cmakeInstallationPath }}"
          filename: "${{ env.msvc2019TargetZip }}"

      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "CrossWindow/cmake-build/${{ env.cmakeInstallationPath }}/${{ env.msvc2019TargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
